<?php
return array(
    '/admin/confirmReviews' => 'admin/СonfirmReviews',
    '/reviews/addReviews' => 'reviews/AddReviews',
    '/admin/reviewsDel' => 'admin/DelReviews',
	'/admin/changePresent' => 'admin/СhangePresent',
	'/admin/changeProduct' => 'admin/СhangeProduct',
	'/admin/changeSweet' => 'admin/СhangeSweet',
	'/admin/changeMix' => 'admin/СhangeMix',
	'/admin/changeIntim' => 'admin/СhangeIntim',
	'/contacts' => 'page/contacts',
	'/about' => 'page/about',
	'/video' => 'page/video',
	'/delivery' => 'page/delivery',
	'/admin' => 'admin/index',
	'/out' => 'admin/exit',
	'/reviews' => 'reviews/list',
	'/present' => 'page/present',
	'/sweets' => 'page/sweets',
	'/mix' => 'page/mix',
	'/intim' => 'page/intim',
	'/AgreementView' => 'page/AgreementView',
	'/mail' => 'page/MailingSection',
	'/sending' => 'home/Mail',
	'/cooperation' => 'page/Сooperation',
	'/order' => 'home/Order',
	'/[a-zA-Z0-9\-.]+' => 'error/notfound',
	'/' => 'home/index',
	);	
?>
